site_name: HKSYU Departments Website CMS user manual
nav:
    - Home: index.md
    - Basic: basic/index.md
    - Documents: 
        - About Documents: documents/index.md
        - Documents Menu: documents/tree-menu.md
        - Content Blocks: documents/content-blocks.md
        - Snippets: documents/snippets.md
        - Navigation & Properties: documents/properties.md
    - Assets:
        - About Asets: assets/index.md
        - Upload Assets: assets/upload-assets.md
        - Replace Asset: assets/replace-asset.md
        - Download Assets: assets/download-assets.md
        - Custom Metadata: assets/custom-metadata.md
        - Get the asset's info: assets/assets-info.md
        - Batch processing: assets/batch-process.md
        - Rollback and Restore: assets/version.md
        - Scheduling: assets/schedule.md
    - Data Objects: 
        - Abour Data Objects: data-objects/index.md
        - SlideBanner: data-objects/slidebanner.md
        - News: data-objects/news.md
        - Events: data-objects/events.md
        - Staffs: data-objects/staffs.md
        - Gallery: data-objects/gallery.md
        - Import/Export Objects: data-objects/import-export.md
    - Forms: forms/index.md
    - Administration: 
        - About Administration: administration/index.md
        - Users and Roles: administration/users.md

theme: readthedocs
